management:
  endpoints:
    web:
        base-path: /
        exposure:
          include: "*"
    shutdown:
      enabled: true
server:
  port: 8080
  servlet:
    context-path: /api/catalog
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/catalog?autoReconnect=true"
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    validation-query: select 1;
    maxActive: 100
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
  flyway:
    flyway:
      sql-migration-prefix: V
      sql-migration-separator: __
      sql-migration-suffixes: .sql
      locations: classpath:db/migration
      repeatable-sql-migration-prefix: R
      baseline-on-migrate: true
      baseline-version: 0